version: '3.9'

services:
  tamagotchi-bot:
    depends_on:
      - tamagotchi-db
    build:
      context: .
    environment:
      - TEST_TAMAGOTCHI_BOT_USERNAME=${TEST_TAMAGOTCHI_BOT_USERNAME}
      - TEST_TAMAGOTCHI_BOT_TOKEN=${TEST_TAMAGOTCHI_BOT_TOKEN}
      - DB_USER_LOCAL=${DB_USER_LOCAL}
      - DB_PASSWORD_LOCAL=${DB_PASSWORD_LOCAL}
    restart: always
  tamagotchi-db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "tamagotchi_db"
      POSTGRES_USER: ${DB_USER_LOCAL}
      POSTGRES_PASSWORD: ${DB_PASSWORD_LOCAL}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
