FROM openjdk:18
ARG JAR_FILE=target/*.jar
ENV TEST_TAMAGOTCHI_BOT_USERNAME=${TEST_TAMAGOTCHI_BOT_USERNAME}
ENV TEST_TAMAGOTCHI_BOT_TOKEN=${TEST_TAMAGOTCHI_BOT_TOKEN}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-DtelegramBot.username=${TEST_TAMAGOTCHI_BOT_USERNAME}","-DtelegramBot.token=${TEST_TAMAGOTCHI_BOT_TOKEN}","-jar","/app.jar"]
